export const SeventySentences = {
  "title": "70 Sentences by Christian Popescu",
  "author": "Connor A. May",
  "body":[
    "And it will be spring. It will be sunny.",
    "He scribbled with a knife on the toilet door of his parents' house.",
    "Only a naive lack of receptivity can explain why his parents painted the door twice a week.",
    "Popescu pasted stickers with flowers and butterflies, pasted playing cards with violets on the bright white tiles.",
    "Thus he founded the daily hermitage of his childhood.",
    "From time to time, from the silver cover of the mirror, he still laughs at the clean face, to be worn in the ecstasy of inspiration, Popescu's face in the fragile years of his childhood.",
    "But, more always, he wrote and cried.",
    "A miniature urinal had also been installed in which these precious stones were collected.",
    "Eternally crowded, eternally assaulted by inspired citizens.",
    "Does the world gather or not gather?",
    "What's more: Great art, like in life!",
    "To me, the poor man, my thoughts run through my brain like the cockroaches, at night, on a dirty kitchen sink.",
    "My thoughts wandered around my head like goats around streetlights on summer nights.",
    "Believe me: everything that goes through our minds is, in any case, a small and petty nonsense compared to the silence of thoughts.",
    "Do I not anticipate myself as an author, as a person, sending a book like this, to the world in general, to an infinite potential of recipients?",
    "For a piece of bread. That's it.",
    "All I can hope for is that we'll stay together as long as possible.",
    "And the sun, the moon and the stars, the light of day and this light of the world were thought to be enlightened.",
    "On the other hand, from tail to head, vice versa.",
    "At first, it's dark on TV.",
    "Popescu is growing and growing.",
    "The flesh gathers on the bones, on any bone, the skin stretches in the blink of an eye, the gala costume is woven again, sewn.",
    "He makes cheerful, hurried gestures towards the device.",
    "Our hero opens his eyes, jumps out of bed and smiles.",
    "He has musical inclinations.",
    "Cursed (too risky) posterity anyway!",
    "Whatever you think, the contrast is too violent.",
    "Like me or other people, he goes through a series of moods, struggling between ideal, theoretical and real and vulgar love.",
    "This would be a clay model doll that, by magic, is resurrected and used as a boy, as a girl in the house.",
    "On his forehead is written the Hebrew word emeth (\"truth\"). Wipe the first letter from your forehead, the golem turns back to clay because meth (without e) means \"death.\"",
    "There was only one beautiful and sad country where most people were sentenced to life in prison.",
    "There was a kind of shabby paradise in which trees grew claws and chicken necks, and especially pig's feet and heads.",
    "But the women of that place were tempted by men to taste them.",
    "There were some dilapidated cemeteries dug with a bulldozer.",
    "How good it would be to write poems for money!",
    "Let's get on the walls, let the world look at us.",
    "I would also sell 30 old, empty inkwells, from which I would claim that Eminescu or Baudelaire drew their ink to scribble their pile of manuscripts.",
    "I mean, a brothel.",
    "The muse is a babysitter in the corner.",
    "And once his dreams come to him, his own dreams, they stare at him, shout and hit him one on the back.",
    "Your naughty mother !!!\r\n\r\nHe then buys a lot of old icons on wood, from which, being nailed, the coffins of the statues of the great poets will be made.",
    "Eventually, the manufacture of an electric train, led by the national poet, was completed.",
    "Of course I was tired of her sagging breasts, hanging on her chest, her heavy, crusty breasts in the night.",
    "\"WHAT IS ART?\" that's what I'm going to cut them with scissors. I'll put a hat on my left.",
    "I'm going to put it on like a sock.",
    "At least that's how I should write a poem (with his foot).",
    "At least that's how I packed my socks.",
    "And then I will go, mad, jumping on one foot on the water, lost in the distance, silent and put only on deeds.",
    "Well, what if you, Lord, don't know what refreshment exercises these people are doing to us?!",
    "Aoleuu !!",
    "In a few years, the painting is taken and a stain appears.",
    "Woe to the mother who made us: like tractor drivers, tan only on the chest after three days and three nights by candlelight!",
    "The poem dreams of being a letter.",
    "The girlfriend is a person.",
    "Of course she got pregnant with me.",
    "I read in the \"Book of Records\" that the highest speed reached by the human body is 289 km / h in the free position upside down, but that speeds of 1005 km / h were also recorded at high altitudes and atmospheres.",
    "I have to be the device that continuously records my own cardiogram.",
    "However, the fibula on her left leg is placed on her left leg. And vice versa.",
    "And that, so much more than the moss on the bark of the trees.",
    "At the asylum, when the old people get into old age, it's like opening a book right at the flower in the press, between the sheets.",
    "Hoping my death has as little to kill as possible.",
    "Poverty with the spirit can also be understood as the absence of the ever-moving thought in the mind, obsessively preoccupied with the fate of the thinker.",
    "The poem is a grave to be desecrated on the inside.",
    "He had planted some chrysanthemums in the garden, he had arranged them, so that they spelled, letter by letter, his name: P-O-P-E-S-C-U.",
    "He came to Popescu's garden every night, took a ray of sunshine, a candle, folded it well, thinned it between his fingers, twisted it, untied it, and filled it with a park.",
    "So they say."
  ]
}